language: node_js
sudo: false
node_js:
  - 10
services:
  - docker
install:
  - npm i
script:
  - npm test
deploy:
  provider: npm
  email: gautaz@users.noreply.github.com
  api_key:
    secure: EijtYX82RpO+QgmtIv+Y1Ao5jAHtA7MGIlQXN/3Z2n6m2sahkHBDKy3cjkjzA3veh7Pd2/NkXfV0tTh5MiMzDKngNPVympZjDnVqsfJ2w0JW5HfUXx8AGy4Hm4diUV2V2TOzha2LivbfItMKG5nZFhUYewgk5b32BvgGvWcuIKFsmIkpwaFP6+nHVbURbXY8isZabywHJhfetKxWj+nboka24/H+9/KmfXUbPu/TD7W/8Fe5KYIMeKeqJKpaDfE7Gemv5PObnuVmJBcA9b5ZK3kQ8Uags2BYk4OxHkHK5/wz6iSlrIxpDfLJDgkLZY32rzGbrtD9Sd+uyOD7y0Mo2817A/SkSe4xdYvZ5aq87Ec3CXO9RJSQkIdaFb8eMrWrO9lup4t0xK72Ed5tk78ABvmoIjUyWlxi4wT1B5SC10CkOG+1dNJAj5fPr9Xbh0n+HM7Fvp6X/ciJUzeYwO8PHUTXXlyMqkBxzlBmOwERJlDCHrLPeRpoSE99IX0u0zgxeftxd/1xv/gg1TrdPsfnsWyugg1I6POLtdUrpV8gYcS5QHWIhBznVQQOqeY7BT+cNrb9UWSMEM6gDZicUpkcu1HDSNDwmymNDcyvlSBDbsdQwYXC8+MNvcDeYqkv0tlK9SWhhd54/yhFaq2EBtTh4SqdBYwz0H8QOurqZ37+BxA=
  on:
    tags: true
